import { DeleteForeverOutlined } from "@mui/icons-material";
import BackspaceOutlinedIcon from '@mui/icons-material/BackspaceOutlined';
import {
    CALCULATOR_KEYBOARD_BUTTON_CLEAR_DATA_TEST_ID,
    CALCULATOR_KEYBOARD_BUTTON_DECIMAL_DATA_TEST_ID,
    CALCULATOR_KEYBOARD_BUTTON_DELETE_DATA_TEST_ID,
    CALCULATOR_KEYBOARD_BUTTON_NUMBER_EIGHT_DATA_TEST_ID,
    CALCULATOR_KEYBOARD_BUTTON_NUMBER_FIVE_DATA_TEST_ID,
    CALCULATOR_KEYBOARD_BUTTON_NUMBER_FOUR_DATA_TEST_ID,
    CALCULATOR_KEYBOARD_BUTTON_NUMBER_NINE_DATA_TEST_ID,
    CALCULATOR_KEYBOARD_BUTTON_NUMBER_ONE_DATA_TEST_ID,
    CALCULATOR_KEYBOARD_BUTTON_NUMBER_SEVEN_DATA_TEST_ID,
    CALCULATOR_KEYBOARD_BUTTON_NUMBER_SIX_DATA_TEST_ID,
    CALCULATOR_KEYBOARD_BUTTON_NUMBER_THREE_DATA_TEST_ID,
    CALCULATOR_KEYBOARD_BUTTON_NUMBER_TWO_DATA_TEST_ID,
    CALCULATOR_KEYBOARD_BUTTON_NUMBER_ZERO_DATA_TEST_ID,
    CALCULATOR_KEYBOARD_BUTTON_PLUS_OR_MINUS_DATA_TEST_ID,
    CALCULATOR_KEYBOARD_BUTTON_TEXT_DECIMAL,
    CALCULATOR_KEYBOARD_BUTTON_TEXT_NUMBER_EIGHT,
    CALCULATOR_KEYBOARD_BUTTON_TEXT_NUMBER_FIVE,
    CALCULATOR_KEYBOARD_BUTTON_TEXT_NUMBER_FOUR,
    CALCULATOR_KEYBOARD_BUTTON_TEXT_NUMBER_NINE,
    CALCULATOR_KEYBOARD_BUTTON_TEXT_NUMBER_ONE,
    CALCULATOR_KEYBOARD_BUTTON_TEXT_NUMBER_SEVEN,
    CALCULATOR_KEYBOARD_BUTTON_TEXT_NUMBER_SIX,
    CALCULATOR_KEYBOARD_BUTTON_TEXT_NUMBER_THREE,
    CALCULATOR_KEYBOARD_BUTTON_TEXT_NUMBER_TWO,
    CALCULATOR_KEYBOARD_BUTTON_TEXT_NUMBER_ZERO,
    CALCULATOR_KEYBOARD_BUTTON_TEXT_PLUS_OR_MINUS
} from ".";
import {
    ECalculatorOperator,
    ECalculatorValue,
    IAction,
    IKeyboard
} from "../types/calculatorType";

const fontSize = 'medium'

export const listKeyboard: IKeyboard[] = [
    {
        dataTestId: CALCULATOR_KEYBOARD_BUTTON_NUMBER_SEVEN_DATA_TEST_ID,
        buttonText: CALCULATOR_KEYBOARD_BUTTON_TEXT_NUMBER_SEVEN,
        value: ECalculatorValue.SEVEN,
    },
    {
        dataTestId: CALCULATOR_KEYBOARD_BUTTON_NUMBER_EIGHT_DATA_TEST_ID,
        buttonText: CALCULATOR_KEYBOARD_BUTTON_TEXT_NUMBER_EIGHT,
        value: ECalculatorValue.EIGHT
    },
    {
        dataTestId: CALCULATOR_KEYBOARD_BUTTON_NUMBER_NINE_DATA_TEST_ID,
        buttonText: CALCULATOR_KEYBOARD_BUTTON_TEXT_NUMBER_NINE,
        value: ECalculatorValue.NINE
    },
    {
        dataTestId: CALCULATOR_KEYBOARD_BUTTON_NUMBER_FOUR_DATA_TEST_ID,
        buttonText: CALCULATOR_KEYBOARD_BUTTON_TEXT_NUMBER_FOUR,
        value: ECalculatorValue.FOUR
    },
    {
        dataTestId: CALCULATOR_KEYBOARD_BUTTON_NUMBER_FIVE_DATA_TEST_ID,
        buttonText: CALCULATOR_KEYBOARD_BUTTON_TEXT_NUMBER_FIVE,
        value: ECalculatorValue.FIVE
    },
    {
        dataTestId: CALCULATOR_KEYBOARD_BUTTON_NUMBER_SIX_DATA_TEST_ID,
        buttonText: CALCULATOR_KEYBOARD_BUTTON_TEXT_NUMBER_SIX,
        value: ECalculatorValue.SIX
    },
    {
        dataTestId: CALCULATOR_KEYBOARD_BUTTON_NUMBER_ONE_DATA_TEST_ID,
        buttonText: CALCULATOR_KEYBOARD_BUTTON_TEXT_NUMBER_ONE,
        value: ECalculatorValue.ONE
    },
    {
        dataTestId: CALCULATOR_KEYBOARD_BUTTON_NUMBER_TWO_DATA_TEST_ID,
        buttonText: CALCULATOR_KEYBOARD_BUTTON_TEXT_NUMBER_TWO,
        value: ECalculatorValue.TWO
    },
    {
        dataTestId: CALCULATOR_KEYBOARD_BUTTON_NUMBER_THREE_DATA_TEST_ID,
        buttonText: CALCULATOR_KEYBOARD_BUTTON_TEXT_NUMBER_THREE,
        value: ECalculatorValue.THREE
    },
    {
        dataTestId: CALCULATOR_KEYBOARD_BUTTON_PLUS_OR_MINUS_DATA_TEST_ID,
        buttonText: CALCULATOR_KEYBOARD_BUTTON_TEXT_PLUS_OR_MINUS,
        value: ECalculatorValue.PLUSORMINUS
    },
    {
        dataTestId: CALCULATOR_KEYBOARD_BUTTON_NUMBER_ZERO_DATA_TEST_ID,
        buttonText: CALCULATOR_KEYBOARD_BUTTON_TEXT_NUMBER_ZERO,
        value: ECalculatorValue.ZERO
    },
    {
        dataTestId: CALCULATOR_KEYBOARD_BUTTON_DECIMAL_DATA_TEST_ID,
        buttonText: CALCULATOR_KEYBOARD_BUTTON_TEXT_DECIMAL,
        value: ECalculatorValue.DECIMAL
    }
]

export const listAction: IAction[] = [
    {
        dataTestId: CALCULATOR_KEYBOARD_BUTTON_CLEAR_DATA_TEST_ID,
        element: <DeleteForeverOutlined fontSize={fontSize} />,
        action: ECalculatorOperator.CLEAR,
    },
    {
        dataTestId: CALCULATOR_KEYBOARD_BUTTON_DELETE_DATA_TEST_ID,
        action: ECalculatorOperator.DELETE,
        element: <BackspaceOutlinedIcon fontSize={fontSize} />,
    }
]